project_id = "lvnpvfxlmzbnylwkvgnq"

[functions.roadmap-hint]
verify_jwt = false

[functions.astra-chat]
verify_jwt = false

[functions.send-quiz-summary]
verify_jwt = false

[functions.send-weekly-digest]
verify_jwt = false
 
 [functions.send-notification-email]
 verify_jwt = false

[functions.send-velocity-reminder]
verify_jwt = false

[functions.analyze-resume]
verify_jwt = false

[functions.generate-ai-content]
verify_jwt = false

[functions.roadmap-chat]
verify_jwt = false

[functions.fetch-coding-profiles]
verify_jwt = false


[functions.parikshaa-generate-questions]
verify_jwt = false

[functions.submit-demo-request]
verify_jwt = false
[functions.assessment-sidecam]
verify_jwt = false

[functions.fetch-jobs]
verify_jwt = false
