import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors'
import { createClient } from 'npm:@supabase/supabase-js@2'

/**
 * AI-text classifier for free-text answers.
 * Uses Lovable AI Gateway (Gemini) to estimate how likely the text was
 * AI-generated. Returns { ai_score: 0..1, label, reasoning }.
 *
 * Body: { session_id, question_id?, text }
 */

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  try {
    const auth = req.headers.get('Authorization') ?? ''
    if (!auth.startsWith('Bearer ')) {
      return new Response(JSON.stringify({ error: 'unauthorized' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }

    const supabase = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!)
    const userRes = await supabase.auth.getUser(auth.replace('Bearer ', ''))
    const user = userRes.data.user
    if (!user) return new Response(JSON.stringify({ error: 'unauthorized' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })

    const { session_id, question_id, text } = await req.json() as { session_id: string; question_id?: string; text: string }
    if (!session_id || typeof text !== 'string' || text.trim().length < 40) {
      return new Response(JSON.stringify({ ok: true, ai_score: null, skipped: 'too_short' }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }

    const { data: sess } = await supabase.from('contest_sessions').select('id,user_id').eq('id', session_id).maybeSingle()
    if (!sess || sess.user_id !== user.id) {
      return new Response(JSON.stringify({ error: 'forbidden' }), { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY')
    if (!LOVABLE_API_KEY) {
      return new Response(JSON.stringify({ error: 'ai_unavailable' }), { status: 503, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }

    const prompt = `You are a forensic AI-text detector. Estimate the probability that the following answer was generated by a large language model (ChatGPT, Claude, Gemini, etc.) rather than written by a human candidate in real time. Consider phrasing uniformity, generic transitions, hedging boilerplate, lack of personal voice or typos, and over-structured lists. Respond ONLY in strict JSON: {"ai_score": <0..1>, "label": "human"|"mixed"|"ai", "reasoning": "<1-2 sentences>"}.\n\nANSWER:\n"""${text.slice(0, 6000)}"""`

    const resp = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${LOVABLE_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [{ role: 'user', content: prompt }],
        response_format: { type: 'json_object' },
      }),
    })
    if (resp.status === 429 || resp.status === 402) {
      return new Response(JSON.stringify({ error: 'rate_limited_or_credits', status: resp.status }), { status: resp.status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }
    if (!resp.ok) {
      return new Response(JSON.stringify({ error: 'ai_error', status: resp.status }), { status: 502, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }
    const j = await resp.json()
    let parsed: { ai_score?: number; label?: string; reasoning?: string } = {}
    try { parsed = JSON.parse(j.choices?.[0]?.message?.content ?? '{}') } catch { /* ignore */ }
    const score = typeof parsed.ai_score === 'number' ? Math.max(0, Math.min(1, parsed.ai_score)) : null

    if (score !== null && score >= 0.75) {
      await supabase.functions.invoke('contest-violation-engine', {
        body: { session_id, category: 'ai_generated_answer', severity: score >= 0.9 ? 'critical' : 'high', meta: { question_id, score, label: parsed.label } },
      })
    }

    return new Response(JSON.stringify({ ok: true, ai_score: score, label: parsed.label ?? null, reasoning: parsed.reasoning ?? null }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (e) {
    return new Response(JSON.stringify({ error: String(e) }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
  }
})
