import { useEffect, useMemo, useRef, useState } from "react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

import {
  Star,
  Trash2,
  MoreVertical,
  ExternalLink,
  Plus,
  ChevronDown,
  ChevronRight,
  CheckCircle2,
  RotateCw,
  Save,
  Info,
  Tag as TagIcon,
  Building2,
  X,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { ChevronScroller } from "@/components/library/coding/ChevronScroller";
import { toast } from "sonner";
import type { JournalEntry, EntryWithDay, Difficulty, EntryStatus } from "../types";
import {
  useCreateEntry,
  useUpdateEntry,
  useDeleteEntry,
  useToggleFavorite,
  useSnoozeEntry,
  useMarkMastered,
} from "../api";
import { detectSource, inferTitleFromUrl } from "../source";
import ReviseInline from "./ReviseInline";

type Row = EntryWithDay;

const DIFFICULTIES: Difficulty[] = ["Easy", "Medium", "Hard"];
const STATUSES: EntryStatus[] = ["solved", "partial", "stuck"];

interface Props {
  entries: Row[];
  dayId?: string | null;
  showAddRow?: boolean;
  showDateCol?: boolean;
  loading?: boolean;
  emptyHint?: string;
  /** When set, new rows are stamped with this session label. */
  sessionLabel?: string | null;
  /** When set, new rows use this ISO timestamp as started_at. */
  sessionStartedAt?: string | null;
}

// ----- Column help copy (shown in header tooltips) -----
const COL_HELP: Record<string, string> = {
  "#": "Row number in the current view.",
  Date: "Day this problem was logged on.",
  Title: "Problem name. Paste a LeetCode/GFG link to auto-fill the title.",
  Topic: "Broad area — e.g. Arrays, Graphs, DP.",
  Pattern: "The technique used — Two Pointers, Sliding Window, BFS, etc.",
  Difficulty: "Problem difficulty: Easy / Medium / Hard.",
  Attempts: "How many tries it took you to solve it.",
  Time: "Minutes you spent on this problem.",
  Status: "solved · partial · stuck — your honest outcome.",
  "Conf.": "Confidence 1–5. Drives the spaced-repetition schedule.",
  "T.C": "Time complexity of your final solution, e.g. O(n log n).",
  "S.C": "Space complexity of your final solution.",
  Companies: "Companies that have asked this problem.",
  Tags: "Free-form labels for filtering — e.g. dp, hard, revisit.",
  "Next rev.": "Next spaced-repetition date generated by the SM-2 scheduler.",
  "★": "Mark as favorite to pin it in filters.",
};

// ----- Colorful chip helpers -----
const CHIP_PALETTE = [
  "bg-amber-500/15 text-amber-300 border-amber-500/30",
  "bg-orange-500/15 text-orange-300 border-orange-500/30",
  "bg-emerald-500/15 text-emerald-300 border-emerald-500/30",
  "bg-amber-500/15 text-amber-300 border-amber-500/30",
  "bg-rose-500/15 text-rose-300 border-rose-500/30",
  "bg-amber-500/15 text-amber-300 border-amber-500/30",
  "bg-orange-500/15 text-orange-300 border-orange-500/30",
  "bg-lime-500/15 text-lime-300 border-lime-500/30",
];
const hashIdx = (s: string) => {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h) % CHIP_PALETTE.length;
};
const chipClass = (s: string) => CHIP_PALETTE[hashIdx(s.toLowerCase())];

const DIFF_STYLE: Record<string, string> = {
  Easy: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30",
  Medium: "bg-amber-500/15 text-amber-300 border-amber-500/30",
  Hard: "bg-rose-500/15 text-rose-300 border-rose-500/30",
};
const STATUS_STYLE: Record<string, string> = {
  solved: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30",
  partial: "bg-amber-500/15 text-amber-300 border-amber-500/30",
  stuck: "bg-rose-500/15 text-rose-300 border-rose-500/30",
};

function Th({
  children,
  className,
  help,
}: {
  children: React.ReactNode;
  className?: string;
  help?: string;
}) {
  return (
    <th className={className}>
      <span className="inline-flex items-center gap-1">
        <span>{children}</span>
        {help && (
          <Tooltip>
            <TooltipTrigger asChild>
              <button
                type="button"
                className="text-muted-foreground/60 hover:text-foreground transition-colors"
                aria-label="What is this column?"
              >
                <Info className="h-3 w-3" />
              </button>
            </TooltipTrigger>
            <TooltipContent side="top" className="max-w-[240px] text-xs">
              {help}
            </TooltipContent>
          </Tooltip>
        )}
      </span>
    </th>
  );
}

export default function PracticeSheet({
  entries,
  dayId,
  showAddRow = false,
  showDateCol = true,
  loading,
  emptyHint = "No entries yet — add your first solve in the row below.",
  sessionLabel = null,
  sessionStartedAt = null,
}: Props) {
  const update = useUpdateEntry();
  const remove = useDeleteEntry();
  const fav = useToggleFavorite();
  const snooze = useSnoozeEntry();
  const master = useMarkMastered();
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  const toggleExpand = (id: string) =>
    setExpanded((s) => {
      const n = new Set(s);
      n.has(id) ? n.delete(id) : n.add(id);
      return n;
    });

  const saveField = (id: string, patch: Partial<JournalEntry>) =>
    update.mutate({ id, patch });

  return (
    <TooltipProvider delayDuration={150}>
      <div className="rounded-xl border border-border/40 bg-card/30 overflow-hidden">
        <ChevronScroller>
          <table className="w-full text-xs min-w-[1500px] border-separate border-spacing-0">
            <thead className="bg-gradient-to-r from-card/80 via-card/60 to-card/80 text-muted-foreground sticky top-0 z-10">
              <tr className="[&>th]:px-2 [&>th]:py-2 [&>th]:font-semibold [&>th]:text-left [&>th]:border-b [&>th]:border-border/40 [&>th]:text-[11px] [&>th]:uppercase [&>th]:tracking-wide whitespace-nowrap">
                <th className="w-8"></th>
                <Th className="w-8" help={COL_HELP["#"]}>#</Th>
                {showDateCol && <Th className="w-20" help={COL_HELP.Date}>Date</Th>}
                <Th className="min-w-[220px]" help={COL_HELP.Title}>Title</Th>
                <Th className="w-28" help={COL_HELP.Topic}>Topic</Th>
                <Th className="w-28" help={COL_HELP.Pattern}>Pattern</Th>
                <Th className="w-28" help={COL_HELP.Difficulty}>Difficulty</Th>
                <Th className="w-16" help={COL_HELP.Attempts}>Att.</Th>
                <Th className="w-16" help={COL_HELP.Time}>Time</Th>
                <Th className="w-24" help={COL_HELP.Status}>Status</Th>
                <Th className="w-16" help={COL_HELP["Conf."]}>Conf.</Th>
                <Th className="w-20" help={COL_HELP["T.C"]}>T.C</Th>
                <Th className="w-20" help={COL_HELP["S.C"]}>S.C</Th>
                <Th className="w-40" help={COL_HELP.Companies}>Companies</Th>
                <Th className="w-40" help={COL_HELP.Tags}>Tags</Th>
                <Th className="w-24" help={COL_HELP["Next rev."]}>Next rev.</Th>
                <Th className="w-8 text-center" help={COL_HELP["★"]}>★</Th>
                <th className="w-8"></th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={18} className="text-center py-6 text-muted-foreground">
                    Loading…
                  </td>
                </tr>
              ) : entries.length === 0 && !showAddRow ? (
                <tr>
                  <td colSpan={18} className="text-center py-6 text-muted-foreground">
                    {emptyHint}
                  </td>
                </tr>
              ) : (
                entries.map((e, i) => (
                  <SheetRow
                    key={e.id}
                    entry={e}
                    index={i + 1}
                    expanded={expanded.has(e.id)}
                    showDateCol={showDateCol}
                    onToggleExpand={() => toggleExpand(e.id)}
                    onSave={(patch) => saveField(e.id, patch)}
                    onDelete={() => {
                      if (confirm(`Delete "${e.title}"?`)) remove.mutate(e.id);
                    }}
                    onToggleFav={() =>
                      fav.mutate({ id: e.id, value: !e.is_favorite })
                    }
                    onSnooze={(d) => snooze.mutate({ id: e.id, days: d })}
                    onMaster={() => master.mutate(e.id)}
                  />
                ))
              )}
              {showAddRow && dayId && (
                <DraftRow
                  dayId={dayId}
                  showDateCol={showDateCol}
                  sessionLabel={sessionLabel}
                  sessionStartedAt={sessionStartedAt}
                />
              )}
            </tbody>
          </table>
        </ChevronScroller>
      </div>
    </TooltipProvider>
  );
}

// ----------------- Row -----------------

function SheetRow({
  entry,
  index,
  expanded,
  showDateCol,
  onToggleExpand,
  onSave,
  onDelete,
  onToggleFav,
  onSnooze,
  onMaster,
}: {
  entry: Row;
  index: number;
  expanded: boolean;
  showDateCol: boolean;
  onToggleExpand: () => void;
  onSave: (patch: Partial<JournalEntry>) => void;
  onDelete: () => void;
  onToggleFav: () => void;
  onSnooze: (days: number) => void;
  onMaster: () => void;
}) {
  return (
    <>
      <tr
        className={cn(
          "border-b border-border/30 hover:bg-card/40 transition-colors [&>td]:px-2 [&>td]:py-1 align-middle",
          entry.mastered_at && "opacity-60",
        )}
      >
        <td>
          <button
            onClick={onToggleExpand}
            className="h-6 w-6 inline-flex items-center justify-center rounded hover:bg-card/60 text-muted-foreground"
            aria-label="Expand"
          >
            {expanded ? (
              <ChevronDown className="h-3 w-3" />
            ) : (
              <ChevronRight className="h-3 w-3" />
            )}
          </button>
        </td>
        <td className="text-muted-foreground tabular-nums">{index}</td>
        {showDateCol && (
          <td className="text-muted-foreground whitespace-nowrap">
            {entry.day?.log_date ?? entry.created_at.slice(0, 10)}
          </td>
        )}
        <td>
          <TitleCell entry={entry} onSave={onSave} />
        </td>
        <td>
          <ChipCell
            value={entry.topic ?? ""}
            onSave={(v) => onSave({ topic: v || null })}
            placeholder="Arrays"
          />
        </td>
        <td>
          <ChipCell
            value={entry.pattern ?? ""}
            onSave={(v) => onSave({ pattern: v || null })}
            placeholder="Two ptr"
          />
        </td>
        <td>
          <BadgeSelect
            value={entry.difficulty ?? ""}
            options={["", ...DIFFICULTIES]}
            styleMap={DIFF_STYLE}
            onSave={(v) => onSave({ difficulty: (v || null) as any })}
            emptyLabel="—"
          />
        </td>
        <td>
          <CellNumber
            value={entry.attempts}
            min={1}
            onSave={(v) => onSave({ attempts: v ?? 1 })}
          />
        </td>
        <td>
          <CellNumber
            value={entry.time_taken_min ?? null}
            min={0}
            onSave={(v) => onSave({ time_taken_min: v })}
            placeholder="—"
          />
        </td>
        <td>
          <BadgeSelect
            value={entry.status}
            options={[...STATUSES]}
            styleMap={STATUS_STYLE}
            onSave={(v) => onSave({ status: v as any })}
          />
        </td>
        <td>
          <CellNumber
            value={entry.confidence ?? null}
            min={1}
            max={5}
            onSave={(v) => onSave({ confidence: v })}
            placeholder="1-5"
          />
        </td>
        <td>
          <CellInput
            value={entry.time_complexity ?? ""}
            onSave={(v) => onSave({ time_complexity: v || null })}
            placeholder="O(n)"
          />
        </td>
        <td>
          <CellInput
            value={entry.space_complexity ?? ""}
            onSave={(v) => onSave({ space_complexity: v || null })}
            placeholder="O(1)"
          />
        </td>
        <td>
          <ChipListCell
            values={entry.companies ?? []}
            onSave={(arr) => onSave({ companies: arr })}
            placeholder="Add company"
            icon={<Building2 className="h-3 w-3" />}
          />
        </td>
        <td>
          <ChipListCell
            values={entry.tags ?? []}
            onSave={(arr) => onSave({ tags: arr })}
            placeholder="Add tag"
            icon={<TagIcon className="h-3 w-3" />}
          />
        </td>
        <td className="text-muted-foreground whitespace-nowrap">
          {entry.mastered_at ? (
            <span className="text-emerald-400 inline-flex items-center gap-1">
              <CheckCircle2 className="h-3 w-3" /> Mastered
            </span>
          ) : (
            entry.next_revision_at ?? "—"
          )}
        </td>
        <td className="text-center">
          <button
            onClick={onToggleFav}
            className="inline-flex items-center justify-center h-6 w-6 rounded hover:bg-card/60"
            aria-label="Favorite"
          >
            <Star
              className={cn(
                "h-3.5 w-3.5",
                entry.is_favorite
                  ? "fill-amber-400 text-amber-400"
                  : "text-muted-foreground",
              )}
            />
          </button>
        </td>
        <td>
          <div className="flex items-center justify-end gap-0.5">
            <ReviseInline
              entry={entry}
              trigger={
                <Button
                  size="sm"
                  variant="ghost"
                  className="h-6 w-6 p-0"
                  title="Revise"
                >
                  <RotateCw className="h-3 w-3" />
                </Button>
              }
            />
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button size="sm" variant="ghost" className="h-6 w-6 p-0">
                  <MoreVertical className="h-3 w-3" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-44">
                <DropdownMenuItem onClick={() => onSnooze(1)}>
                  Snooze 1 day
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => onSnooze(3)}>
                  Snooze 3 days
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => onSnooze(7)}>
                  Snooze 1 week
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem onClick={onMaster}>
                  <CheckCircle2 className="h-3 w-3 mr-2" /> Mark mastered
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem
                  onClick={onDelete}
                  className="text-destructive focus:text-destructive"
                >
                  <Trash2 className="h-3 w-3 mr-2" /> Delete
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </td>
      </tr>
      {expanded && (
        <tr className="bg-card/20 border-b border-border/30">
          <td colSpan={showDateCol ? 18 : 17} className="px-4 py-3">
            <ExpandedDetails entry={entry} onSave={onSave} />
          </td>
        </tr>
      )}
    </>
  );
}

function ExpandedDetails({
  entry,
  onSave,
}: {
  entry: JournalEntry;
  onSave: (patch: Partial<JournalEntry>) => void;
}) {
  return (
    <div className="grid md:grid-cols-2 gap-3">
      <LongField
        label="Mistakes"
        value={entry.mistakes ?? ""}
        onSave={(v) => onSave({ mistakes: v || null })}
        placeholder="What went wrong this time?"
      />
      <LongField
        label="Learnings"
        value={entry.learnings ?? ""}
        onSave={(v) => onSave({ learnings: v || null })}
        placeholder="Key insight, pattern, trick…"
      />
      <LongField
        label="Notes"
        value={entry.notes_md ?? ""}
        onSave={(v) => onSave({ notes_md: v || null })}
        placeholder="Markdown notes"
        rows={4}
      />
      <LongField
        label={`Code snippet${entry.language ? ` (${entry.language})` : ""}`}
        value={entry.code_snippet ?? ""}
        onSave={(v) => onSave({ code_snippet: v || null })}
        placeholder="Paste your solution"
        rows={4}
        mono
      />
      <div className="md:col-span-2">
        <div className="text-[11px] text-muted-foreground mb-1">Algorithm</div>
        <CellInput
          value={entry.algorithm ?? ""}
          onSave={(v) => onSave({ algorithm: v || null })}
          placeholder="e.g. Kadane, BFS, DP top-down"
          full
        />
      </div>
    </div>
  );
}

function LongField({
  label,
  value,
  onSave,
  placeholder,
  rows = 3,
  mono = false,
}: {
  label: string;
  value: string;
  onSave: (v: string) => void;
  placeholder?: string;
  rows?: number;
  mono?: boolean;
}) {
  const [v, setV] = useState(value);
  const [dirty, setDirty] = useState(false);
  useEffect(() => {
    setV(value);
    setDirty(false);
  }, [value]);
  return (
    <div>
      <div className="flex items-center justify-between mb-1">
        <div className="text-[11px] text-muted-foreground">{label}</div>
        {dirty && (
          <Button
            size="sm"
            variant="ghost"
            className="h-6 px-2 text-[11px]"
            onClick={() => {
              onSave(v);
              setDirty(false);
            }}
          >
            <Save className="h-3 w-3 mr-1" /> Save
          </Button>
        )}
      </div>
      <Textarea
        value={v}
        rows={rows}
        placeholder={placeholder}
        onChange={(e) => {
          setV(e.target.value);
          setDirty(true);
        }}
        onBlur={() => {
          if (dirty) {
            onSave(v);
            setDirty(false);
          }
        }}
        className={cn("text-xs", mono && "font-mono")}
      />
    </div>
  );
}

// ----------------- Cells -----------------

function CellInput({
  value,
  onSave,
  placeholder,
  full,
}: {
  value: string;
  onSave: (v: string) => void;
  placeholder?: string;
  full?: boolean;
}) {
  const [v, setV] = useState(value);
  useEffect(() => setV(value), [value]);
  return (
    <Input
      value={v}
      onChange={(e) => setV(e.target.value)}
      onBlur={() => {
        if (v !== value) onSave(v);
      }}
      onKeyDown={(e) => {
        if (e.key === "Enter") (e.target as HTMLInputElement).blur();
        if (e.key === "Escape") setV(value);
      }}
      placeholder={placeholder}
      className={cn(
        "h-7 px-1.5 text-xs bg-transparent border-transparent hover:border-border focus:border-border/80",
        full && "w-full",
      )}
    />
  );
}

function CellNumber({
  value,
  onSave,
  min,
  max,
  placeholder,
}: {
  value: number | null;
  onSave: (v: number | null) => void;
  min?: number;
  max?: number;
  placeholder?: string;
}) {
  const [v, setV] = useState<string>(value == null ? "" : String(value));
  useEffect(() => setV(value == null ? "" : String(value)), [value]);
  return (
    <Input
      type="number"
      value={v}
      min={min}
      max={max}
      onChange={(e) => setV(e.target.value)}
      onBlur={() => {
        if (v === "") {
          if (value != null) onSave(null);
          return;
        }
        let n = Number(v);
        if (Number.isNaN(n)) return;
        if (min != null) n = Math.max(min, n);
        if (max != null) n = Math.min(max, n);
        if (n !== value) onSave(n);
      }}
      placeholder={placeholder}
      className="h-7 px-1.5 text-xs bg-transparent border-transparent hover:border-border focus:border-border/80 w-full"
    />
  );
}

function CellSelect({
  value,
  options,
  labels,
  onSave,
}: {
  value: string;
  options: string[];
  labels?: Record<string, string>;
  onSave: (v: string) => void;
}) {
  return (
    <Select value={value || "__none__"} onValueChange={(v) => onSave(v === "__none__" ? "" : v)}>
      <SelectTrigger className="h-7 px-1.5 text-xs bg-transparent border-transparent hover:border-border">
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        {options.map((o) => (
          <SelectItem key={o || "__none__"} value={o || "__none__"} className="text-xs capitalize">
            {labels?.[o] ?? (o || "—")}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// ----------------- Colorful cells -----------------

function ChipCell({
  value,
  onSave,
  placeholder,
}: {
  value: string;
  onSave: (v: string) => void;
  placeholder?: string;
}) {
  const [editing, setEditing] = useState(false);
  const [v, setV] = useState(value);
  useEffect(() => setV(value), [value]);

  if (editing) {
    return (
      <Input
        autoFocus
        value={v}
        onChange={(e) => setV(e.target.value)}
        onBlur={() => {
          setEditing(false);
          if (v !== value) onSave(v);
        }}
        onKeyDown={(e) => {
          if (e.key === "Enter") (e.target as HTMLInputElement).blur();
          if (e.key === "Escape") {
            setV(value);
            setEditing(false);
          }
        }}
        placeholder={placeholder}
        className="h-7 px-1.5 text-xs"
      />
    );
  }
  return (
    <button
      type="button"
      onClick={() => setEditing(true)}
      className="w-full text-left"
    >
      {value ? (
        <span
          className={cn(
            "inline-flex items-center px-2 py-0.5 rounded-full text-[11px] border font-medium",
            chipClass(value),
          )}
        >
          {value}
        </span>
      ) : (
        <span className="text-muted-foreground/60 text-[11px] italic px-1">
          {placeholder ?? "—"}
        </span>
      )}
    </button>
  );
}

function BadgeSelect({
  value,
  options,
  styleMap,
  onSave,
  emptyLabel,
}: {
  value: string;
  options: string[];
  styleMap: Record<string, string>;
  onSave: (v: string) => void;
  emptyLabel?: string;
}) {
  return (
    <Select
      value={value || "__none__"}
      onValueChange={(v) => onSave(v === "__none__" ? "" : v)}
    >
      <SelectTrigger
        className={cn(
          "h-7 px-2 text-[11px] border font-semibold capitalize w-full justify-between gap-1",
          value && styleMap[value]
            ? styleMap[value]
            : "bg-transparent border-transparent text-muted-foreground hover:border-border",
        )}
      >
        <SelectValue placeholder={emptyLabel ?? "—"} />
      </SelectTrigger>
      <SelectContent>
        {options.map((o) => (
          <SelectItem
            key={o || "__none__"}
            value={o || "__none__"}
            className="text-xs capitalize"
          >
            {o ? (
              <span
                className={cn(
                  "inline-flex items-center px-2 py-0.5 rounded-full text-[11px] border font-semibold",
                  styleMap[o] ?? "",
                )}
              >
                {o}
              </span>
            ) : (
              emptyLabel ?? "—"
            )}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

function ChipListCell({
  values,
  onSave,
  placeholder,
  icon,
}: {
  values: string[];
  onSave: (next: string[]) => void;
  placeholder?: string;
  icon?: React.ReactNode;
}) {
  const [draft, setDraft] = useState("");
  const add = () => {
    const v = draft.trim();
    if (!v) return;
    if (values.includes(v)) {
      setDraft("");
      return;
    }
    onSave([...values, v]);
    setDraft("");
  };
  const remove = (v: string) => onSave(values.filter((x) => x !== v));

  return (
    <Popover>
      <PopoverTrigger asChild>
        <button
          type="button"
          className="w-full flex flex-wrap gap-1 items-center px-1 py-1 rounded hover:bg-card/60 min-h-[28px] text-left"
        >
          {values.length === 0 && (
            <span className="text-muted-foreground/60 text-[11px] italic inline-flex items-center gap-1">
              {icon} {placeholder ?? "Add"}
            </span>
          )}
          {values.slice(0, 3).map((v) => (
            <span
              key={v}
              className={cn(
                "inline-flex items-center px-1.5 py-0.5 rounded-full text-[10px] border font-medium",
                chipClass(v),
              )}
            >
              {v}
            </span>
          ))}
          {values.length > 3 && (
            <span className="text-[10px] text-muted-foreground">
              +{values.length - 3}
            </span>
          )}
        </button>
      </PopoverTrigger>
      <PopoverContent className="w-64 p-2 space-y-2">
        <div className="flex flex-wrap gap-1">
          {values.length === 0 && (
            <span className="text-[11px] text-muted-foreground">No items yet.</span>
          )}
          {values.map((v) => (
            <span
              key={v}
              className={cn(
                "inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] border font-medium",
                chipClass(v),
              )}
            >
              {v}
              <button
                type="button"
                onClick={() => remove(v)}
                className="hover:text-foreground"
                aria-label={`Remove ${v}`}
              >
                <X className="h-2.5 w-2.5" />
              </button>
            </span>
          ))}
        </div>
        <div className="flex gap-1">
          <Input
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder={placeholder}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                add();
              }
            }}
            className="h-7 text-xs"
          />
          <Button size="sm" className="h-7 px-2 text-xs" onClick={add}>
            Add
          </Button>
        </div>
      </PopoverContent>
    </Popover>
  );
}

function TitleCell({
  entry,
  onSave,
}: {
  entry: JournalEntry;
  onSave: (patch: Partial<JournalEntry>) => void;
}) {
  const primary = entry.links?.[0];
  const extras = (entry.links ?? []).slice(1);
  return (
    <div className="flex items-center gap-1 min-w-0">
      <CellInput
        value={entry.title}
        onSave={(v) => v && v !== entry.title && onSave({ title: v })}
        full
      />
      {primary?.url && (
        <a
          href={primary.url}
          target="_blank"
          rel="noreferrer"
          className="shrink-0 text-muted-foreground hover:text-primary"
          title={primary.url}
        >
          <ExternalLink className="h-3 w-3" />
        </a>
      )}
      {extras.length > 0 && (
        <Popover>
          <PopoverTrigger asChild>
            <button className="shrink-0 text-[10px] px-1.5 h-5 rounded bg-card/60 border border-border/40 text-muted-foreground hover:text-foreground">
              +{extras.length}
            </button>
          </PopoverTrigger>
          <PopoverContent className="w-64 p-2 text-xs">
            <div className="font-semibold text-[11px] text-muted-foreground mb-1">
              More links
            </div>
            <ul className="space-y-1">
              {extras.map((l, i) => (
                <li key={i}>
                  <a
                    href={l.url}
                    target="_blank"
                    rel="noreferrer"
                    className="text-primary hover:underline truncate block"
                  >
                    {l.label || l.url}
                  </a>
                </li>
              ))}
            </ul>
          </PopoverContent>
        </Popover>
      )}
    </div>
  );
}

// ----------------- Draft (add) row -----------------

function DraftRow({
  dayId,
  showDateCol,
  sessionLabel,
  sessionStartedAt,
}: {
  dayId: string;
  showDateCol: boolean;
  sessionLabel?: string | null;
  sessionStartedAt?: string | null;
}) {
  const create = useCreateEntry();
  const [title, setTitle] = useState("");
  const [url, setUrl] = useState("");
  const [topic, setTopic] = useState("");
  const [pattern, setPattern] = useState("");
  const [difficulty, setDifficulty] = useState<string>("");
  const [attempts, setAttempts] = useState<string>("1");
  const [time, setTime] = useState<string>("");
  const titleRef = useRef<HTMLInputElement>(null);

  const reset = () => {
    setTitle("");
    setUrl("");
    setTopic("");
    setPattern("");
    setDifficulty("");
    setAttempts("1");
    setTime("");
    requestAnimationFrame(() => titleRef.current?.focus());
  };

  const save = async () => {
    const finalTitle = title.trim() || (url ? inferTitleFromUrl(url) : "");
    if (!finalTitle) {
      toast.error("Title is required");
      return;
    }
    const links = url ? [{ label: detectSource(url) ?? "link", url }] : [];
    await create.mutateAsync({
      day_id: dayId,
      title: finalTitle,
      links,
      topic: topic || null,
      pattern: pattern || null,
      difficulty: (difficulty || null) as any,
      attempts: Math.max(1, Number(attempts) || 1),
      time_taken_min: time === "" ? null : Math.max(0, Number(time)),
      source: detectSource(url) ?? null,
      session_label: sessionLabel || null,
      started_at: sessionStartedAt || null,
    });
    reset();
  };

  const onKey = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      save();
    }
  };

  return (
    <tr className="bg-primary/[0.03] border-t-2 border-dashed border-border/40 [&>td]:px-2 [&>td]:py-1.5">
      <td className="text-muted-foreground">
        <Plus className="h-3 w-3" />
      </td>
      <td className="text-muted-foreground">+</td>
      {showDateCol && <td className="text-muted-foreground text-[10px]">today</td>}
      <td>
        <div className="flex gap-1">
          <Input
            ref={titleRef}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            onKeyDown={onKey}
            placeholder="Problem title…"
            className="h-7 px-1.5 text-xs"
          />
          <Input
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            onKeyDown={onKey}
            onBlur={() => {
              if (url && !title) setTitle(inferTitleFromUrl(url));
            }}
            placeholder="Paste link"
            className="h-7 px-1.5 text-xs w-32"
          />
        </div>
      </td>
      <td>
        <Input
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          onKeyDown={onKey}
          placeholder="Topic"
          className="h-7 px-1.5 text-xs"
        />
      </td>
      <td>
        <Input
          value={pattern}
          onChange={(e) => setPattern(e.target.value)}
          onKeyDown={onKey}
          placeholder="Pattern"
          className="h-7 px-1.5 text-xs"
        />
      </td>
      <td>
        <Select value={difficulty || "__none__"} onValueChange={(v) => setDifficulty(v === "__none__" ? "" : v)}>
          <SelectTrigger className="h-7 px-1.5 text-xs">
            <SelectValue placeholder="—" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="__none__" className="text-xs">—</SelectItem>
            {DIFFICULTIES.map((d) => (
              <SelectItem key={d} value={d} className="text-xs">
                {d}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </td>
      <td>
        <Input
          type="number"
          min={1}
          value={attempts}
          onChange={(e) => setAttempts(e.target.value)}
          onKeyDown={onKey}
          className="h-7 px-1.5 text-xs"
        />
      </td>
      <td>
        <Input
          type="number"
          min={0}
          value={time}
          onChange={(e) => setTime(e.target.value)}
          onKeyDown={onKey}
          placeholder="min"
          className="h-7 px-1.5 text-xs"
        />
      </td>
      <td colSpan={8} className="text-[10px] text-muted-foreground">
        Press Enter to save · expand row after to add notes, code & companies
      </td>
      <td className="text-right">
        <Button
          size="sm"
          onClick={save}
          disabled={create.isPending}
          className="h-7 px-2 text-xs"
        >
          <Plus className="h-3 w-3 mr-1" /> Add
        </Button>
      </td>
    </tr>
  );
}
