// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
var getEnv = (name) => {
  const deno = globalThis.Deno;
  const denoValue = deno?.env?.get?.(name);
  if (denoValue) return denoValue;
  return process.env[name];
};
var createUserSupabaseClient = (ctx) => {
  const supabaseUrl = getEnv("SUPABASE_URL");
  const supabaseKey = getEnv("SUPABASE_PUBLISHABLE_KEY") ?? getEnv("SUPABASE_ANON_KEY");
  if (!supabaseUrl || !supabaseKey) {
    throw new Error("Backend environment is missing SUPABASE_URL or anon key.");
  }
  return createClient(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
};
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Parikshaa user's id, email, and profile summary. Use this to confirm the MCP connection is authenticated.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const email = ctx.getUserEmail() ?? null;
    const supabase = createUserSupabaseClient(ctx);
    const { data: profile, error } = await supabase.from("profiles").select("full_name, avatar_url").eq("user_id", userId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const payload = { user_id: userId, email, profile: profile ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-folders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.23.8";
var getEnv2 = (name) => {
  const deno = globalThis.Deno;
  const denoValue = deno?.env?.get?.(name);
  if (denoValue) return denoValue;
  return process.env[name];
};
var createUserSupabaseClient2 = (ctx) => {
  const supabaseUrl = getEnv2("SUPABASE_URL");
  const supabaseKey = getEnv2("SUPABASE_PUBLISHABLE_KEY") ?? getEnv2("SUPABASE_ANON_KEY");
  if (!supabaseUrl || !supabaseKey) {
    throw new Error("Backend environment is missing SUPABASE_URL or anon key.");
  }
  return createClient2(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
};
var list_folders_default = defineTool2({
  name: "list_folders",
  title: "List my folders",
  description: "List the signed-in Parikshaa user's custom folders (name, description, color, timestamps). Scoped by RLS to the current user.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max folders to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createUserSupabaseClient2(ctx);
    const { data, error } = await supabase.from("user_folders").select("id, name, description, color, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Found ${data?.length ?? 0} folders:
${JSON.stringify(data, null, 2)}`
        }
      ],
      structuredContent: { folders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-quiz-attempts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.23.8";

// src/lib/mcp/tools/_shared.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.8";
var getEnv3 = (name) => {
  const deno = globalThis.Deno;
  return deno?.env?.get?.(name) ?? process.env[name];
};
var createUserSupabaseClient3 = (ctx) => {
  const url = getEnv3("SUPABASE_URL");
  const key = getEnv3("SUPABASE_PUBLISHABLE_KEY") ?? getEnv3("SUPABASE_ANON_KEY");
  if (!url || !key) throw new Error("Backend env missing SUPABASE_URL or anon key.");
  return createClient3(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
};
var jsonResult = (label, data) => ({
  content: [{ type: "text", text: `${label}
${JSON.stringify(data, null, 2)}` }],
  structuredContent: { data }
});
var errResult = (msg) => ({
  content: [{ type: "text", text: msg }],
  isError: true
});

// src/lib/mcp/tools/list-quiz-attempts.ts
var list_quiz_attempts_default = defineTool3({
  name: "list_quiz_attempts",
  title: "List quiz attempts",
  description: "Recent quiz results for the signed-in user (score, topic, timestamps).",
  inputSchema: { limit: z2.number().int().min(1).max(100).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("quiz_results").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} quiz attempts:`, data);
  }
});

// src/lib/mcp/tools/get-progress-stats.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_progress_stats_default = defineTool4({
  name: "get_progress_stats",
  title: "Get progress stats",
  description: "Total XP, level, and recent XP transactions for the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const userId = ctx.getUserId();
    const [txRes, recentRes] = await Promise.all([
      sb.from("xp_transactions").select("amount").eq("user_id", userId),
      sb.from("xp_transactions").select("*").eq("user_id", userId).order("created_at", { ascending: false }).limit(10)
    ]);
    if (txRes.error) return errResult(txRes.error.message);
    const totalXp = (txRes.data ?? []).reduce((s, r) => s + (r.amount ?? 0), 0);
    return jsonResult("Progress:", { totalXp, recent: recentRes.data ?? [] });
  }
});

// src/lib/mcp/tools/list-folder-items.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.23.8";
var list_folder_items_default = defineTool5({
  name: "list_folder_items",
  title: "List folder items",
  description: "Items saved inside a specific folder owned by the signed-in user.",
  inputSchema: {
    folder_id: z3.string().uuid().describe("Folder UUID (from list_folders)."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ folder_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("user_folder_items").select("*").eq("folder_id", folder_id).order("created_at", { ascending: false }).limit(limit ?? 100);
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} items:`, data);
  }
});

// src/lib/mcp/tools/list-solved-problems.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.23.8";
var list_solved_problems_default = defineTool6({
  name: "list_solved_problems",
  title: "List solved problems",
  description: "Coding problem solutions saved by the signed-in user.",
  inputSchema: { limit: z4.number().int().min(1).max(200).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("user_problem_solutions").select("*").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} solutions:`, data);
  }
});

// src/lib/mcp/tools/list-topic-progress.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.23.8";
var list_topic_progress_default = defineTool7({
  name: "list_topic_progress",
  title: "List topic progress",
  description: "Per-topic learning progress for the signed-in user.",
  inputSchema: { limit: z5.number().int().min(1).max(500).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("user_topic_progress").select("*").order("updated_at", { ascending: false }).limit(limit ?? 100);
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} topics:`, data);
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z6 } from "npm:zod@^3.23.8";
var list_journal_entries_default = defineTool8({
  name: "list_journal_entries",
  title: "List DSA journal entries",
  description: "Practice journal entries (problems logged, notes, difficulty, revisions).",
  inputSchema: {
    limit: z6.number().int().min(1).max(200).optional(),
    status: z6.string().optional().describe("Optional status filter (e.g. 'solved').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    let q = sb.from("practice_journal_entries").select("id,title,topic,pattern,difficulty,status,tags,solved_clean,time_taken_min,next_revision_at,is_favorite,created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} entries:`, data);
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z7 } from "npm:zod@^3.23.8";
var list_notifications_default = defineTool9({
  name: "list_notifications",
  title: "List notifications",
  description: "Recent notifications for the signed-in user.",
  inputSchema: {
    limit: z7.number().int().min(1).max(100).optional(),
    unread_only: z7.boolean().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    let q = sb.from("notifications").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (unread_only) q = q.eq("read", false);
    const { data, error } = await q;
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} notifications:`, data);
  }
});

// src/lib/mcp/tools/list-goals.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.1";
var list_goals_default = defineTool10({
  name: "list_goals",
  title: "List user goals",
  description: "Active learning goals for the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("user_goals").select("*").order("created_at", { ascending: false });
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} goals:`, data);
  }
});

// src/lib/mcp/tools/search-coding-problems.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z8 } from "npm:zod@^3.23.8";
var search_coding_problems_default = defineTool11({
  name: "search_coding_problems",
  title: "Search coding problems",
  description: "Search Parikshaa's published coding problems by title or difficulty.",
  inputSchema: {
    query: z8.string().optional().describe("Substring match against title."),
    difficulty: z8.enum(["easy", "medium", "hard"]).optional(),
    limit: z8.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, difficulty, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    let q = sb.from("coding_problems").select("slug,title,difficulty,topics").eq("is_published", true).limit(limit ?? 25);
    if (query) q = q.ilike("title", `%${query}%`);
    if (difficulty) q = q.eq("difficulty", difficulty);
    const { data, error } = await q;
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} problems:`, data);
  }
});

// src/lib/mcp/tools/list-platform-stats.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.1";
var list_platform_stats_default = defineTool12({
  name: "list_platform_stats",
  title: "List platform stats",
  description: "Synced coding platform stats (LeetCode, Codeforces, etc.) for the user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("user_platform_stats").select("*");
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} platform rows:`, data);
  }
});

// src/lib/mcp/tools/create-folder.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z9 } from "npm:zod@^3.23.8";
var create_folder_default = defineTool13({
  name: "create_folder",
  title: "Create folder",
  description: "Create a new custom folder for the signed-in user.",
  inputSchema: {
    name: z9.string().min(1).max(100),
    description: z9.string().max(500).optional(),
    color: z9.string().max(20).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, description, color }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("user_folders").insert({ user_id: ctx.getUserId(), name, description, color }).select().single();
    if (error) return errResult(error.message);
    return jsonResult("Folder created:", data);
  }
});

// src/lib/mcp/tools/add-folder-item.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z10 } from "npm:zod@^3.23.8";
var add_folder_item_default = defineTool14({
  name: "add_folder_item",
  title: "Add item to folder",
  description: "Save an item (question/problem) to one of the user's folders.",
  inputSchema: {
    folder_id: z10.string().uuid(),
    item_type: z10.string().min(1).describe("e.g. 'dsa', 'sql', 'interview', 'coding-problem'"),
    item_id: z10.string().min(1).describe("Slug or UUID of the item.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ folder_id, item_type, item_id }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("user_folder_items").insert({ folder_id, item_type, item_id }).select().single();
    if (error) return errResult(error.message);
    return jsonResult("Item added:", data);
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z11 } from "npm:zod@^3.23.8";
var create_journal_entry_default = defineTool15({
  name: "create_journal_entry",
  title: "Create DSA journal entry",
  description: "Log a solved / attempted problem to the practice journal.",
  inputSchema: {
    title: z11.string().min(1).max(200),
    topic: z11.string().optional(),
    pattern: z11.string().optional(),
    difficulty: z11.enum(["easy", "medium", "hard"]).optional(),
    time_taken_min: z11.number().int().min(0).optional(),
    solved_clean: z11.boolean().optional(),
    notes_md: z11.string().optional(),
    status: z11.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("practice_journal_entries").insert({ user_id: ctx.getUserId(), ...input }).select().single();
    if (error) return errResult(error.message);
    return jsonResult("Entry created:", data);
  }
});

// src/lib/mcp/tools/mark-notifications-read.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z12 } from "npm:zod@^3.23.8";
var mark_notifications_read_default = defineTool16({
  name: "mark_notifications_read",
  title: "Mark notifications read",
  description: "Mark specific notifications (or all) as read for the signed-in user.",
  inputSchema: {
    notification_ids: z12.array(z12.string().uuid()).optional().describe("If omitted, marks ALL unread as read.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ notification_ids }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    let q = sb.from("notifications").update({ read: true }).eq("user_id", ctx.getUserId()).eq("read", false);
    if (notification_ids?.length) q = q.in("id", notification_ids);
    const { data, error } = await q.select("id");
    if (error) return errResult(error.message);
    return jsonResult(`Marked ${data?.length ?? 0} as read.`, data);
  }
});

// src/lib/mcp/tools/db-universal.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z13 } from "npm:zod@^3.23.8";
var tableSchema = z13.string().min(1).max(64).regex(/^[a-z_][a-z0-9_]*$/, "Invalid table name");
var filterSchema = z13.record(z13.union([z13.string(), z13.number(), z13.boolean(), z13.null()])).optional().describe("Equality filters: { column: value }. RLS scopes results to the signed-in user.");
var dbSelectTool = defineTool17({
  name: "db_select",
  title: "Query any table",
  description: "SELECT from any public table. RLS scopes results to the signed-in user. Use for reading ANY feature's data (quizzes, goals, folders, journal, contests, achievements, notifications, resume, outreach, blog, jobs, ratings, etc.).",
  inputSchema: {
    table: tableSchema,
    columns: z13.string().optional().describe("Comma-separated columns (default '*')."),
    filters: filterSchema,
    order_by: z13.string().optional().describe("Column name to order by."),
    ascending: z13.boolean().optional(),
    limit: z13.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ table, columns, filters, order_by, ascending, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    let q = sb.from(table).select(columns ?? "*").limit(limit ?? 50);
    if (filters) for (const [k, v] of Object.entries(filters)) q = q.eq(k, v);
    if (order_by) q = q.order(order_by, { ascending: ascending ?? false });
    const { data, error } = await q;
    if (error) return errResult(`${error.code ?? ""} ${error.message}`);
    return jsonResult(`Found ${data?.length ?? 0} rows in ${table}:`, data);
  }
});
var dbInsertTool = defineTool17({
  name: "db_insert",
  title: "Insert into any table",
  description: "INSERT rows into any public table. RLS's WITH CHECK enforces ownership \u2014 if user_id is required, set it to the signed-in user's id (returned by whoami).",
  inputSchema: {
    table: tableSchema,
    values: z13.record(z13.unknown()).describe("Column \u2192 value object for the new row.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ table, values }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from(table).insert(values).select();
    if (error) return errResult(`${error.code ?? ""} ${error.message}`);
    return jsonResult(`Inserted into ${table}:`, data);
  }
});
var dbUpdateTool = defineTool17({
  name: "db_update",
  title: "Update rows in any table",
  description: "UPDATE rows in any public table matching the given filters. RLS restricts which rows can be modified.",
  inputSchema: {
    table: tableSchema,
    filters: z13.record(z13.union([z13.string(), z13.number(), z13.boolean(), z13.null()])).describe("Equality filters selecting which rows to update. Required to prevent full-table updates."),
    values: z13.record(z13.unknown()).describe("Columns \u2192 new values.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ table, filters, values }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    if (!filters || Object.keys(filters).length === 0)
      return errResult("Refusing to update without filters.");
    const sb = createUserSupabaseClient3(ctx);
    let q = sb.from(table).update(values);
    for (const [k, v] of Object.entries(filters)) q = q.eq(k, v);
    const { data, error } = await q.select();
    if (error) return errResult(`${error.code ?? ""} ${error.message}`);
    return jsonResult(`Updated ${data?.length ?? 0} rows in ${table}:`, data);
  }
});
var dbDeleteTool = defineTool17({
  name: "db_delete",
  title: "Delete rows from any table",
  description: "DELETE rows from any public table matching the given filters. RLS restricts which rows can be deleted. Filters are required.",
  inputSchema: {
    table: tableSchema,
    filters: z13.record(z13.union([z13.string(), z13.number(), z13.boolean(), z13.null()])).describe("Equality filters selecting which rows to delete. Required.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ table, filters }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    if (!filters || Object.keys(filters).length === 0)
      return errResult("Refusing to delete without filters.");
    const sb = createUserSupabaseClient3(ctx);
    let q = sb.from(table).delete();
    for (const [k, v] of Object.entries(filters)) q = q.eq(k, v);
    const { data, error } = await q.select();
    if (error) return errResult(`${error.code ?? ""} ${error.message}`);
    return jsonResult(`Deleted ${data?.length ?? 0} rows from ${table}:`, data);
  }
});

// src/lib/mcp/tools/publish-coding-problem.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z14 } from "npm:zod@^3.23.8";
var problemSchema = z14.object({
  slug: z14.string().min(2).max(80).regex(/^[a-z0-9-]+$/, "slug must be lowercase-with-dashes"),
  title: z14.string().min(3).max(150),
  difficulty: z14.enum(["easy", "medium", "hard"]),
  description: z14.string().min(30, "description too short (min 30 chars)"),
  topics: z14.array(z14.string().min(1)).min(1, "at least 1 topic required"),
  examples: z14.array(z14.record(z14.unknown())).min(1, "at least 1 example required"),
  constraints: z14.array(z14.string()).optional(),
  hints: z14.array(z14.string()).optional(),
  cpu_time_limit_sec: z14.number().positive().optional(),
  memory_limit_kb: z14.number().int().positive().optional(),
  mcq: z14.record(z14.unknown()).optional(),
  is_contest_pool: z14.boolean().optional()
});
var testSchema = z14.object({
  input: z14.string(),
  expected_output: z14.string(),
  is_sample: z14.boolean().optional(),
  weight: z14.number().optional()
});
var publishCodingProblemTool = defineTool18({
  name: "publish_coding_problem",
  title: "Publish coding problem (validated)",
  description: "Validate + publish a coding problem. Enforces required fields, requires \u22652 tests, and handles slug conflicts. If the slug already exists, use if_exists='update' to overwrite (auto-snapshots current version first) or if_exists='error' (default) to abort and prompt the caller.",
  inputSchema: {
    problem: z14.object({
      slug: z14.string(),
      title: z14.string(),
      difficulty: z14.string(),
      description: z14.string(),
      topics: z14.array(z14.string()),
      examples: z14.array(z14.record(z14.unknown())),
      constraints: z14.array(z14.string()).optional(),
      hints: z14.array(z14.string()).optional(),
      cpu_time_limit_sec: z14.number().optional(),
      memory_limit_kb: z14.number().int().optional(),
      mcq: z14.record(z14.unknown()).optional(),
      is_contest_pool: z14.boolean().optional()
    }),
    tests: z14.array(testSchema).min(2, "at least 2 tests required to publish"),
    starter_code: z14.array(z14.object({ language: z14.string(), code: z14.string() })).optional(),
    if_exists: z14.enum(["error", "update"]).optional().describe("Default 'error'. 'update' overwrites and snapshots the previous version."),
    version_note: z14.string().optional().describe("Note stored on the snapshot when overwriting.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ problem, tests, starter_code, if_exists, version_note }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const parsed = problemSchema.safeParse(problem);
    if (!parsed.success) {
      return errResult(
        "Validation failed. Missing/invalid fields:\n" + JSON.stringify(parsed.error.flatten().fieldErrors, null, 2)
      );
    }
    const p = parsed.data;
    const sb = createUserSupabaseClient3(ctx);
    const { data: existing, error: exErr } = await sb.from("coding_problems").select("slug, title, is_published").eq("slug", p.slug).maybeSingle();
    if (exErr) return errResult(`Slug check failed: ${exErr.message}`);
    if (existing && (if_exists ?? "error") === "error") {
      return errResult(
        `Slug "${p.slug}" already exists (title: "${existing.title}", published: ${existing.is_published}). Re-call with if_exists="update" to overwrite (a version snapshot will be saved for rollback), or choose a different slug.`
      );
    }
    let snapshotVersion = null;
    if (existing) {
      const [{ data: fullRow }, { data: curTests }, { data: curStarter }] = await Promise.all([
        sb.from("coding_problems").select("*").eq("slug", p.slug).maybeSingle(),
        sb.from("coding_problem_tests").select("*").eq("problem_slug", p.slug),
        sb.from("coding_problem_starter_code").select("*").eq("problem_slug", p.slug)
      ]);
      const { data: latest } = await sb.from("coding_problem_versions").select("version_number").eq("slug", p.slug).order("version_number", { ascending: false }).limit(1).maybeSingle();
      snapshotVersion = (latest?.version_number ?? 0) + 1;
      const { error: snapErr } = await sb.from("coding_problem_versions").insert({
        slug: p.slug,
        version_number: snapshotVersion,
        snapshot: fullRow ?? {},
        tests_snapshot: curTests ?? [],
        starter_snapshot: curStarter ?? [],
        note: version_note ?? `Auto snapshot before overwrite`,
        created_by: ctx.getUserId()
      });
      if (snapErr) return errResult(`Snapshot failed (aborted before overwrite): ${snapErr.message}`);
    }
    const { error: upErr } = await sb.from("coding_problems").upsert({ ...p, is_published: true, created_by: ctx.getUserId() }, { onConflict: "slug" });
    if (upErr) return errResult(`Publish failed: ${upErr.message}`);
    await sb.from("coding_problem_tests").delete().eq("problem_slug", p.slug);
    const { error: tErr } = await sb.from("coding_problem_tests").insert(tests.map((t) => ({ ...t, problem_slug: p.slug })));
    if (tErr) return errResult(`Tests insert failed: ${tErr.message}`);
    if (starter_code?.length) {
      await sb.from("coding_problem_starter_code").delete().eq("problem_slug", p.slug);
      const { error: sErr } = await sb.from("coding_problem_starter_code").insert(starter_code.map((s) => ({ ...s, problem_slug: p.slug })));
      if (sErr) return errResult(`Starter code insert failed: ${sErr.message}`);
    }
    return jsonResult(
      existing ? `Overwritten "${p.slug}". Previous state saved as version ${snapshotVersion}. Use rollback_coding_problem to restore.` : `Published new problem "${p.slug}" with ${tests.length} tests.`,
      { slug: p.slug, snapshotVersion, tests: tests.length, starters: starter_code?.length ?? 0 }
    );
  }
});
var listCodingProblemVersionsTool = defineTool18({
  name: "list_coding_problem_versions",
  title: "List coding problem versions",
  description: "List saved version snapshots for a coding problem slug (admin only).",
  inputSchema: { slug: z14.string() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data, error } = await sb.from("coding_problem_versions").select("id, version_number, note, created_by, created_at").eq("slug", slug).order("version_number", { ascending: false });
    if (error) return errResult(error.message);
    return jsonResult(`Found ${data?.length ?? 0} versions for "${slug}":`, data);
  }
});
var rollbackCodingProblemTool = defineTool18({
  name: "rollback_coding_problem",
  title: "Rollback coding problem",
  description: "Restore a coding problem (and its tests + starter code) from a saved version snapshot. Also snapshots the CURRENT state before rolling back, so a rollback is itself reversible.",
  inputSchema: {
    slug: z14.string(),
    version_number: z14.number().int().positive()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ slug, version_number }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data: ver, error: vErr } = await sb.from("coding_problem_versions").select("*").eq("slug", slug).eq("version_number", version_number).maybeSingle();
    if (vErr) return errResult(vErr.message);
    if (!ver) return errResult(`No version ${version_number} found for "${slug}".`);
    const [{ data: curRow }, { data: curTests }, { data: curStarter }, { data: latest }] = await Promise.all([
      sb.from("coding_problems").select("*").eq("slug", slug).maybeSingle(),
      sb.from("coding_problem_tests").select("*").eq("problem_slug", slug),
      sb.from("coding_problem_starter_code").select("*").eq("problem_slug", slug),
      sb.from("coding_problem_versions").select("version_number").eq("slug", slug).order("version_number", { ascending: false }).limit(1).maybeSingle()
    ]);
    const preRollbackVersion = (latest?.version_number ?? 0) + 1;
    if (curRow) {
      await sb.from("coding_problem_versions").insert({
        slug,
        version_number: preRollbackVersion,
        snapshot: curRow,
        tests_snapshot: curTests ?? [],
        starter_snapshot: curStarter ?? [],
        note: `Auto snapshot before rollback to v${version_number}`,
        created_by: ctx.getUserId()
      });
    }
    const snap = ver.snapshot;
    const { error: upErr } = await sb.from("coding_problems").upsert(snap, { onConflict: "slug" });
    if (upErr) return errResult(`Restore failed: ${upErr.message}`);
    await sb.from("coding_problem_tests").delete().eq("problem_slug", slug);
    const tests = ver.tests_snapshot ?? [];
    if (tests.length) await sb.from("coding_problem_tests").insert(tests);
    await sb.from("coding_problem_starter_code").delete().eq("problem_slug", slug);
    const starters = ver.starter_snapshot ?? [];
    if (starters.length) await sb.from("coding_problem_starter_code").insert(starters);
    return jsonResult(
      `Rolled back "${slug}" to version ${version_number}. Pre-rollback state saved as version ${preRollbackVersion}.`,
      { slug, restoredVersion: version_number, preRollbackVersion }
    );
  }
});

// src/lib/mcp/tools/publish-coding-solution.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z15 } from "npm:zod@^3.23.8";
var publishCodingSolutionTool = defineTool19({
  name: "publish_coding_solution",
  title: "Publish coding problem reference solution",
  description: "Upsert reference solution(s) for a published coding problem. Provide `problem_slug` and one or more `{ lang_id, code }` entries. Common lang_id values: 'python', 'javascript', 'cpp', 'java'. Existing solutions for the same (slug, lang_id) are overwritten.",
  inputSchema: {
    problem_slug: z15.string().min(2),
    solutions: z15.array(
      z15.object({
        lang_id: z15.string().min(1).describe("Language identifier (e.g. python, javascript, cpp, java)"),
        code: z15.string().min(1)
      })
    ).min(1, "at least one solution required")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ problem_slug, solutions }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const sb = createUserSupabaseClient3(ctx);
    const { data: exists, error: exErr } = await sb.from("coding_problems").select("slug").eq("slug", problem_slug).maybeSingle();
    if (exErr) return errResult(`Problem lookup failed: ${exErr.message}`);
    if (!exists) return errResult(`No coding problem with slug "${problem_slug}". Publish the problem first with publish_coding_problem.`);
    const rows = solutions.map((s) => ({
      problem_slug,
      lang_id: s.lang_id,
      code: s.code,
      updated_at: (/* @__PURE__ */ new Date()).toISOString()
    }));
    const { error: upErr } = await sb.from("coding_problem_reference_solutions").upsert(rows, { onConflict: "problem_slug,lang_id" });
    if (upErr) return errResult(`Publish solution failed: ${upErr.message}`);
    return jsonResult(
      `Published ${rows.length} reference solution(s) for "${problem_slug}".`,
      { problem_slug, languages: rows.map((r) => r.lang_id) }
    );
  }
});

// src/lib/mcp/tools/publish-coding-bundle.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z16 } from "npm:zod@^3.23.8";
var problemSchema2 = z16.object({
  slug: z16.string().min(2).max(80).regex(/^[a-z0-9-]+$/, "slug must be lowercase-with-dashes"),
  title: z16.string().min(3).max(150),
  difficulty: z16.enum(["easy", "medium", "hard"]),
  description: z16.string().min(30),
  topics: z16.array(z16.string().min(1)).min(1),
  examples: z16.array(z16.record(z16.unknown())).min(1),
  constraints: z16.array(z16.string()).optional(),
  hints: z16.array(z16.string()).optional(),
  cpu_time_limit_sec: z16.number().positive().optional(),
  memory_limit_kb: z16.number().int().positive().optional(),
  mcq: z16.record(z16.unknown()).optional(),
  is_contest_pool: z16.boolean().optional()
});
var testSchema2 = z16.object({
  input: z16.string(),
  expected_output: z16.string(),
  is_sample: z16.boolean().optional(),
  weight: z16.number().optional()
});
var publishCodingBundleTool = defineTool20({
  name: "publish_coding_bundle",
  title: "Publish coding problem + solutions bundle",
  description: "One-shot publish: problem + tests + starter code + reference solutions for multiple languages. Snapshots the previous version when overwriting. Use this instead of calling publish_coding_problem and publish_coding_solution separately.",
  inputSchema: {
    problem: z16.object({
      slug: z16.string(),
      title: z16.string(),
      difficulty: z16.string(),
      description: z16.string(),
      topics: z16.array(z16.string()),
      examples: z16.array(z16.record(z16.unknown())),
      constraints: z16.array(z16.string()).optional(),
      hints: z16.array(z16.string()).optional(),
      cpu_time_limit_sec: z16.number().optional(),
      memory_limit_kb: z16.number().int().optional(),
      mcq: z16.record(z16.unknown()).optional(),
      is_contest_pool: z16.boolean().optional()
    }),
    tests: z16.array(testSchema2).min(2, "at least 2 tests required"),
    starter_code: z16.array(z16.object({ language: z16.string(), code: z16.string() })).optional(),
    solutions: z16.array(z16.object({ lang_id: z16.string().min(1), code: z16.string().min(1) })).min(1, "at least one reference solution required"),
    if_exists: z16.enum(["error", "update"]).optional(),
    version_note: z16.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ problem, tests, starter_code, solutions, if_exists, version_note }, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const parsed = problemSchema2.safeParse(problem);
    if (!parsed.success) {
      return errResult(
        "Validation failed:\n" + JSON.stringify(parsed.error.flatten().fieldErrors, null, 2)
      );
    }
    const p = parsed.data;
    const sb = createUserSupabaseClient3(ctx);
    const { data: existing, error: exErr } = await sb.from("coding_problems").select("slug, title").eq("slug", p.slug).maybeSingle();
    if (exErr) return errResult(`Slug check failed: ${exErr.message}`);
    if (existing && (if_exists ?? "error") === "error") {
      return errResult(
        `Slug "${p.slug}" already exists. Re-call with if_exists="update" to overwrite (a version snapshot will be saved).`
      );
    }
    let snapshotVersion = null;
    if (existing) {
      const [{ data: fullRow }, { data: curTests }, { data: curStarter }, { data: curSolutions }, { data: latest }] = await Promise.all([
        sb.from("coding_problems").select("*").eq("slug", p.slug).maybeSingle(),
        sb.from("coding_problem_tests").select("*").eq("problem_slug", p.slug),
        sb.from("coding_problem_starter_code").select("*").eq("problem_slug", p.slug),
        sb.from("coding_problem_reference_solutions").select("*").eq("problem_slug", p.slug),
        sb.from("coding_problem_versions").select("version_number").eq("slug", p.slug).order("version_number", { ascending: false }).limit(1).maybeSingle()
      ]);
      snapshotVersion = (latest?.version_number ?? 0) + 1;
      const { error: snapErr } = await sb.from("coding_problem_versions").insert({
        slug: p.slug,
        version_number: snapshotVersion,
        snapshot: { ...fullRow ?? {}, _solutions: curSolutions ?? [] },
        tests_snapshot: curTests ?? [],
        starter_snapshot: curStarter ?? [],
        note: version_note ?? "Auto snapshot before bundle overwrite",
        created_by: ctx.getUserId()
      });
      if (snapErr) return errResult(`Snapshot failed (aborted): ${snapErr.message}`);
    }
    const { error: upErr } = await sb.from("coding_problems").upsert({ ...p, is_published: true, created_by: ctx.getUserId() }, { onConflict: "slug" });
    if (upErr) return errResult(`Publish failed: ${upErr.message}`);
    await sb.from("coding_problem_tests").delete().eq("problem_slug", p.slug);
    const { error: tErr } = await sb.from("coding_problem_tests").insert(tests.map((t) => ({ ...t, problem_slug: p.slug })));
    if (tErr) return errResult(`Tests insert failed: ${tErr.message}`);
    if (starter_code?.length) {
      await sb.from("coding_problem_starter_code").delete().eq("problem_slug", p.slug);
      const { error: sErr } = await sb.from("coding_problem_starter_code").insert(starter_code.map((s) => ({ ...s, problem_slug: p.slug })));
      if (sErr) return errResult(`Starter code insert failed: ${sErr.message}`);
    }
    const solRows = solutions.map((s) => ({
      problem_slug: p.slug,
      lang_id: s.lang_id,
      code: s.code,
      updated_at: (/* @__PURE__ */ new Date()).toISOString()
    }));
    const { error: solErr } = await sb.from("coding_problem_reference_solutions").upsert(solRows, { onConflict: "problem_slug,lang_id" });
    if (solErr) return errResult(`Solutions upsert failed: ${solErr.message}`);
    return jsonResult(
      existing ? `Bundle overwritten "${p.slug}" (previous saved as v${snapshotVersion}). Tests=${tests.length}, starters=${starter_code?.length ?? 0}, solutions=${solRows.length}.` : `Bundle published "${p.slug}" \u2014 ${tests.length} tests, ${starter_code?.length ?? 0} starters, ${solRows.length} solutions.`,
      {
        slug: p.slug,
        snapshotVersion,
        tests: tests.length,
        starters: starter_code?.length ?? 0,
        solutions: solRows.map((r) => r.lang_id)
      }
    );
  }
});

// src/lib/mcp/tools/ensure-admin-access.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.20.1";
var ensureAdminAccessTool = defineTool21({
  name: "ensure_admin_access",
  title: "Ensure admin access for this MCP client",
  description: "Grant the signed-in MCP user the 'admin' role so publish tools work. Idempotent \u2014 safe to call at the start of every session. Only OAuth-client tokens (Claude, ChatGPT connectors) are allowed; regular app sessions are rejected.",
  inputSchema: {},
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errResult("Not authenticated");
    const clientId = ctx.getClientId?.();
    if (!clientId) {
      return errResult(
        "This tool is only callable by OAuth MCP clients (Claude, ChatGPT). Your token has no client_id claim."
      );
    }
    const sb = createUserSupabaseClient3(ctx);
    const { error } = await sb.rpc("grant_admin_to_self");
    if (error) return errResult(`grant_admin_to_self failed: ${error.message}`);
    return jsonResult(
      `Admin role ensured for user ${ctx.getUserId()} (client=${clientId}).`,
      { user_id: ctx.getUserId(), client_id: clientId, role: "admin" }
    );
  }
});

// src/lib/mcp/index.ts
var projectRef = "elzftqnehcmnouptaqee";
var mcp_default = defineMcp({
  name: "parikshaa-mcp",
  title: "Parikshaa",
  version: "0.1.0",
  instructions: "Parikshaa MCP server for admins/owners. Tools act as the signed-in user (RLS enforced) but admin/owner roles have broad read/write across all features. Start with `ensure_admin_access` then `whoami`. For any table: db_select (simple), db_query (advanced filters), db_insert/db_update/db_delete. For DB functions: db_rpc. For files: storage_list/upload/delete/signed_url. For business logic: invoke_edge_function. For access control: admin_manage_role. Coding-content publishing: publish_coding_bundle / publish_coding_problem / publish_coding_solution.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_folders_default,
    list_folder_items_default,
    list_quiz_attempts_default,
    get_progress_stats_default,
    list_solved_problems_default,
    list_topic_progress_default,
    list_journal_entries_default,
    list_notifications_default,
    list_goals_default,
    search_coding_problems_default,
    list_platform_stats_default,
    create_folder_default,
    add_folder_item_default,
    create_journal_entry_default,
    mark_notifications_read_default,
    dbSelectTool,
    dbInsertTool,
    dbUpdateTool,
    dbDeleteTool,
    publishCodingProblemTool,
    listCodingProblemVersionsTool,
    rollbackCodingProblemTool,
    publishCodingSolutionTool,
    publishCodingBundleTool,
    ensureAdminAccessTool
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
